name: validvision
description: The Gp Flutter project.
version: 1.0.0

dependencies:
  cupertino_icons: ^0.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flare_flutter: ^2.0.1
  image_picker: ^0.6.3+4
  smooth_page_indicator: ^0.1.3
  shared_preferences: ^0.5.6+2
  redux: ^4.0.0
  http: ^0.12.0+4
  flutter_redux: ^0.6.0
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Arabolical
      fonts:
        - asset: assets/fonts/arabolical.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/UbuntuMedium.ttf
  assets:
    - assets/logo.png
    - assets/logo.flr
    - assets/ai_vision.jpg
    - assets/healthy_eye.png
    - assets/take_pic.png
    - assets/doctors.png