name: validvision
description: The Gp Flutter project.
version: 1.0.0

dependencies:
  cupertino_icons: ^0.1.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  redux: ^4.0.0
  flutter_redux: ^0.6.0
  flutter_launcher_icons: ^0.7.4
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Arabolical
      fonts:
        - asset: assets/fonts/arabolical.ttf
  assets:
    - assets/logo.png